version: "3.8"
services:
  app:
    container_name: app-nekoverse-breeding
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    working_dir: /home/node/app
    command: npm start
    restart: unless-stopped
    tty: true
    volumes: 
      - .:/home/node/app
      - /home/node/app/node_modules
    networks:
      - nekoverse-breeding-network
    depends_on:
      - database
    ports:
      - 5000:3000
    environment:
      APP_ENV: dev
      PORT: 3000
      DB_HOST: database
      DB_DATABASE: nekobreeding
      DB_USERNAME: root
      DB_PASSWORD: 1234
      DB_PORT: 5432

  database:
    container_name: postgres-nekoverse-breeding
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - nekoverse-breeding-database:/var/lib/postgres
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: nekobreeding
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    networks:
      - nekoverse-breeding-network
  
networks:
  nekoverse-breeding-network:
    driver: bridge

volumes:
  nekoverse-breeding-database:
    driver: local